----5-10. Identifying Rows Generated by the GROUP BY Arguments

-----------------------------

SELECT CASE WHEN GROUPING(ReorderPoint) = 1 THEN '--GROUP--'
ELSE CONVERT(VARCHAR(15), ReorderPoint)
END AS ReorderPointCalc,
    ReorderPoint,
    CASE WHEN GROUPING(Size) = 1 THEN '--GROUP--'
ELSE CONVERT(VARCHAR(15), Size)
END AS SizeCalc,
    Size,
    CASE WHEN GROUPING(ReorderPoint) = 0 AND GROUPING(Size) = 1 THEN 'Size Total'
WHEN GROUPING(ReorderPoint) = 1 AND GROUPING(Size) = 0 THEN 'ReorderPoint
Total'
WHEN GROUPING(ReorderPoint) = 1 AND GROUPING(Size) = 1 THEN 'Grand Total'
ELSE 'Regular Row'
END AS RowType,
    SUM(StandardCost) AS Total
FROM Production.Product
WHERE ReorderPoint = 3
GROUP BY CUBE(ReorderPoint, Size);

----------------------------------------- Present the data


-----------------------------

    
-----------------------------




-----------------------------

    
-----------------------------




