CREATE TABLE [dbo].[CreditCards](
	[CreditCardType] [nvarchar](25) NULL,
	[AutoID] [int] IDENTITY(1,1) NOT NULL,
	[LastUpdatedTimestamp] [timestamp] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [CCards_PK] PRIMARY KEY NONCLUSTERED 
(
	[AutoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
